name: Deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: Distrospace

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.CR_USER }}
          password: ${{ secrets.CR_PAT }}
          
      - name: Debug
        run: |
          pwd
          ls -la
          docker --version
          docker compose version
          echo "CR_USER: ${{ secrets.CR_USER }}"

      - name: Build and push vkbot
        run: |
          docker build -t ghcr.io/${{ secrets.CR_USER }}/vkbot:latest .
          docker push ghcr.io/${{ secrets.CR_USER }}/vkbot:latest

      - name: Deploy locally
        run: |
          cd /var/www/localhost
          docker compose pull
          docker compose up -d